
# The code in this file was initially generated by ChatGPT 
# and subsequently reviewed and revised.


import numpy as np
from mpi4py import MPI
from dolfinx import mesh, fem
import ufl
from petsc4py import PETSc
from dolfinx.fem.petsc import LinearProblem
from dolfinx.io import XDMFFile




def validate_prism_gravity(L, H, W, nx, ny, nz, lam, mu, 
                           gravity,
                           rtol, max_iter):
    
    domain = mesh.create_box(
        MPI.COMM_WORLD,
        [np.array([0.0, 0.0, 0.0]),
        np.array([L, H, W])],
        [nx-1, ny-1, nz-1],
        cell_type=mesh.CellType.tetrahedron,
    )


    # Function space 
    # "Lagrange": Standard nodal basis
    # 1: Polynomial degree. Degree 1 means Linear inside each tetrahedron
    # (3,) means: This is a vector-valued space of dimension 3.
    V = fem.functionspace(domain, ("Lagrange", 1, (3,)))


    # Material
    def epsilon(u):
        return ufl.sym(ufl.grad(u))

    def sigma(u):
        return lam * ufl.tr(epsilon(u)) * ufl.Identity(3) + 2 * mu * epsilon(u)


    def left_boundary(x):
        return np.isclose(x[0], 0.0)

    # Find all degrees of freedom in space V whose coordinates satisfy left_boundary.
    # Since V is vector-valued (3 DOFs per node),
    # this finds all DOFs attached to nodes where x=0
    # So we have selected the left face of the beam.
    bc_dofs = fem.locate_dofs_geometrical(V, left_boundary)

    # This creates a Dirichlet boundary condition object.
    # At those DOFs, enforce displacement = (0,0,0)
    # So physically, we are clamping the left face. 
    # The beam is fixed there.
    bc = fem.dirichletbc(PETSc.ScalarType((0.0, 0.0, 0.0)), bc_dofs, V)


    # Variational problem
    u = ufl.TrialFunction(V)
    v = ufl.TestFunction(V)
    #gravity is a body force density
    f = fem.Constant(domain, PETSc.ScalarType((0.0, 0.0, gravity)))
    #Constant vector body force.This is applied everywhere in the volume.
    a = ufl.inner(sigma(u), epsilon(v)) * ufl.dx
    Lform = ufl.dot(f, v) * ufl.dx


    problem = LinearProblem(
        a,
        Lform,
        bcs=[bc],
        petsc_options_prefix="elasticity",
        petsc_options={
            "ksp_type": "cg",
            "ksp_rtol": rtol,
            #"ksp_atol": 0.0,
            "ksp_max_it": max_iter,
            "pc_type": "none"
        }
    )

    uh = problem.solve()


    # Nr. of tetrahedra check
    num_cells = domain.topology.index_map(domain.topology.dim).size_local
    print(f"Number of tetrahedra: {num_cells}")


    # displacement
    coords = domain.geometry.x
    u_vals = uh.x.array.reshape(-1,3)

    np.save(f"data/fenics_gravity_{nx}_{ny}_{nz}_coords.npy", coords)
    np.save(f"data/fenics_gravity_{nx}_{ny}_{nz}_u.npy", u_vals)



    # displacement magnitude at every node
    u_mag = np.linalg.norm(u_vals, axis=1)

    # local maximum 
    local_max_idx = np.argmax(u_mag)
    local_max_val = u_mag[local_max_idx]
    local_max_coord = coords[local_max_idx]
    local_ux, local_uy, local_uz = u_vals[local_max_idx]


    comm = MPI.COMM_WORLD

    # gather all local maxima to rank 0
    all_max_vals = comm.gather(local_max_val, root=0)
    all_max_coords = comm.gather(local_max_coord, root=0)
    all_max_u = comm.gather((local_ux, local_uy, local_uz), root=0)

    if comm.rank == 0:
        # find global maximum among ranks
        global_rank_idx = np.argmax(all_max_vals)

        print("Max displacement magnitude:", all_max_vals[global_rank_idx])
        print("Coordinates:", all_max_coords[global_rank_idx])
        print("ux =", all_max_u[global_rank_idx][0])
        print("uy =", all_max_u[global_rank_idx][1])
        print("uz =", all_max_u[global_rank_idx][2])


    # Export to XDMF
    uh.name = "u"

    with XDMFFile(domain.comm, "data/prism_gravity_solution.xdmf", "w") as xdmf:
        xdmf.write_mesh(domain)
        xdmf.write_function(uh)








L = 8.0
H = 1.0
W = 1.0


gravity = 0.05

lam = 100.0
mu = 100.0

rtol = 1e-6
max_iter = 10000


mesh_list = [
    (65, 9, 9),
    (89, 12, 12),
    (121, 16, 16),
    (169, 22, 22),
]



for (nx, ny, nz) in mesh_list:
    validate_prism_gravity(L, H, W, nx, ny, nz, lam, mu, 
                       gravity, 
                       rtol, max_iter)